[env:16u2]
platform = atmelavr
board = atmega16u2
board_build.mcu = atmega16u2
board_build.f_cpu = 16000000L

extra_scripts = 
    pre:scripts/process_fonts.py
    pre:scripts/clean_fonts.py

build_flags =
    -I fonts
    -I lib/lufa/LUFA
    -I lib/lufa/LUFA/Drivers/USB

upload_protocol = custom
# upload_command = avrdude -p m16u2 -c usbasp -U flash:w:$SOURCE:i
upload_command = /usr/bin/avrdude -C/etc/avrdude.conf -v -p atmega16u2 -c "arduino_as_isp" -P /dev/ttyUSB0 -U flash:w:$SOURCE:i
#upload_command = avrdude -C$PROJECT_PACKAGES_DIR/tool-avrdude/avrdude.conf -c arduino -P /dev/ttyUSB0 -b 19200 -v -v -p atmega16u2


